build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:19.0.0
labels:
  org.opencontainers.image.title: "Argon ONE OLED Display"
  org.opencontainers.image.description: "Argon ONE OLED Display management for Home Assistant"
  org.opencontainers.image.source: "https://github.com/LPeberdy/argon-one-v5-oled-ha"
  org.opencontainers.image.licenses: "MIT"
